### ISSUE TITLE
[Roadmap] Milestone 2.0

### ISSUE THREAD

**Issue by Rel1cx** [Rel1cx/eslint-react#335]
### System Requirements

Minimum supported versions:

- [x] Node.js: 20.19.0
- [x] ESLint: 9.36.0
- [x] TypeScript: 5.9.2

### Package Distribution

- [x] Publish ESM-Only packages

### Plugins (with ecological niche explanation)

- [x] `eslint-plugin-react-x` - X Rules (renderer-agnostic, compatible with x-platform)
- [x] `eslint-plugin-react-dom` - DOM Specific rules for React DOM
- [x] `eslint-plugin-react-web-api` - Rules for interacting with Web APIs
- [x] `eslint-plugin-react-hooks-extra` - Extra Hooks rules for React
- [x] `eslint-plugin-react-naming-convention` - Naming convention rules designed for React projects
- ... (Free to combine with other plugins from the community)

### Add codemod feature to rules that can be transformed (using auto-fix) safely

- [x] `react-x/no-component-did-update`
- [x] `react-x/no-component-will-receive-props`
- [x] `react-x/no-component-will-update`
- [x] `react-x/no-context-provider`
- [x] `react-x/no-forward-ref`
- [x] `react-x/no-string-refs`

### Add auto-fix feature to rules that can be auto-fixed safely

- [x] `react-x/prefer-namespace-import`
- [x] `react-dom/prefer-namespace-import`

### Add suggestion-fix feature to rules that can be fixed interactively

- [x] `react-dom/no-missing-button-type`
- [x] `react-dom/no-missing-iframe-sandbox`
- [x] `react-dom/no-unsafe-target-blank`

### New Rules

- [x] `react-x/jsx-no-comment-textnodes` - Disallow text nodes with comments in JSX (Replaces `no-comment-textnodes`)
- [x] `react-x/no-context-provider` - Replaces usages of `<Context.Provider>` with `<Context>` (React 19)
- [x] `react-x/no-forward-ref` - Replaces usages of `forwardRef` with passing `ref` as a prop (React 19)
- [x] `react-x/no-use-context` - Replaces usages of `useContext` with `use` (React 19)
- [x] `react-x/prefer-namespace-import` - Enforces the use of namespace imports for React (Replaces `prefer-react-namespace-import`)
- [x] `react-dom/no-hydrate` - Replaces usages of `ReactDom.hydrate()` with `hydrateRoot()` (React 19)
- [x] `react-dom/no-render` - Replaces usages of `ReactDom.render()` with `createRoot(node).render()` (React 19)
- [x] `react-dom/no-use-form-state` - Replaces the usages of `useFormState()` to use `useActionState()` (React 19)
- [x] `react-dom/prefer-namespace-import` - Enforces the use of namespace imports for ReactDOM
- [x] `naming-convention/context-name` - Enforces context name to be a valid component name with the suffix `Context` (React 19)

### Removed Rules

- [x] `react-x/avoid-shorthand-boolean` - Replaced by `jsx-shorthand-boolean`
- [x] `react-x/avoid-shorthand-fragment` - Replaced by `jsx-shorthand-fragment`
- [x] `react-x/no-comment-textnodes` - Replaced by `jsx-no-comment-textnodes`
- [x] `react-x/prefer-react-namespace-import` - Replaced by `prefer-namespace-import`
- [x] `react-x/prefer-shorthand-boolean` - Replaced by `jsx-shorthand-boolean`
- [x] `react-x/prefer-shorthand-fragment` - Replaced by `jsx-shorthand-fragment`
- [x] `react-hooks-extra/no-direct-set-state-in-use-layout-effect` - Merged into `hooks-extra/no-direct-set-state-in-use-effect`

**Comment by karlhorky** [comment]
> * eslint-plugin-react-dom-a11y

Exciting! Maybe this could be considered a replacement for [`eslint-plugin-jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y)? Would be great to be able to move off of this plugin too.

If this fits the goals of the ESLint React project, maybe it would also be good to consider additional rules from [the `eslint-plugin-jsx-a11y` rules](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules)

**Comment by Rel1cx** [comment]
> > * eslint-plugin-react-dom-a11y
> 
> Exciting! Maybe this could be considered a replacement for [`eslint-plugin-jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y)? Would be great to be able to move off of this plugin too.
> 
> If this fits the goals of the ESLint React project, maybe it would also be good to consider additional rules from [the `eslint-plugin-jsx-a11y` rules](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules)

The e18e community has launched a new plugin [eslint-plugin-jsx-a11y-x](https://github.com/es-tooling/eslint-plugin-jsx-a11y-x/issues/1), which seems to meet the need for a replacement for eslint-plugin-jsx-a11y.
As for eslint-react, if needed, we may consider continuing to migrate Svelte's Accessibility warnings as an alternative, but the priority will be lower.

**Comment by rikisamurai** [comment]
Hi! Recently, I've been migrating from `eslint-plugin-react` to `@eslint-react/eslint-plugin` and find its rules very useful. However, I've noticed that that they don't seem to support fixable. Are there any plans to add fixable support in future updates?

**Comment by Rel1cx** [comment]
> Hi! Recently, I've been migrating from `eslint-plugin-react` to `@eslint-react/eslint-plugin` and find its rules very useful. However, I've noticed that that they don't seem to support fixable. Are there any plans to add fixable support in future updates?

Thank you for trying out this new ESLint plugin. In fact, we are in the process of adding fixable support, so please follow the updates in the recent versions.

**Comment by JounQin** [comment]
@karlhorky Just FYI, https://github.com/es-tooling/eslint-plugin-jsx-a11y-x has been cleaned up.
